{
 "title": "PPS L1 - Electrical Measurements",
 "tags": [ "PPSL1_Electrical" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Process_Bucket", "query": "${VAR_PROCESS_BUCKET}" }
  ]
 },
 "panels": [
  { "title": "BC1 - Rotary Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Drive Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DriveState\")\r\n\r\n  //|> map(fn: (r) => ( { r with DriveStatus: if r._value == \"Running\" then 1\r\n  //                                          else if r._value == \"Stopped\" then 0\r\n   //                                         else\r\n   //                                             0\r\n   //                     })  )"
    }
   ]
  },
  {
   "title": "Current Assymetry [%]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentAssymetry\")\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> yield(name: \"raw\")\r\n  |> movingAverage(n: 10)\r\n  |> yield(name: \"avarage\")\r\n"
    }
   ]
  },
  {
   "title": "Current [A]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_Current\" or  r[\"_field\"] == \"L2_Current\" or r[\"_field\"] == \"L3_Current\")\r\n  |> aggregateWindow(every: 10ms, fn: mean, createEmpty: false)\r\n  //|> yield(name:\"mean\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Current Integral",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_CurrIntegral\" or r[\"_field\"] == \"L2_CurrIntegral\" or r[\"_field\"] == \"L3_CurrIntegral\" )\r\n\r\n"
    }
   ]
  },
  {
   "title": "Anomaly ratio - Current Integral Phase L1",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L1_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
    }
   ]
  },
  {
   "title": "Anomaly ratio - Current Integral Phase L2",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L2_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
    }
   ]
  },
  {
   "title": "Anomaly ratio - Current Integral Phase L3",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L3_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
    }
   ]
  },
  {
   "title": "Anomaly trend  [%] - Current Integral",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L1_CurrIntegral_AnomalyRatio\"  ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L1_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L1_CurrIntegral_AnomalyRatio\"])\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L2_CurrIntegral_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L2_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L2_CurrIntegral_AnomalyRatio\"])"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L3_CurrIntegral_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L3_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L3_CurrIntegral_AnomalyRatio\"])"
    }
   ]
  },
  {
   "title": "Inrush Current [A]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_InrushCurr\" or r[\"_field\"] == \"L2_InrushCurr\" or r[\"_field\"] == \"L3_InrushCurr\" )\r\n\r\n"
    }
   ]
  },
  {
   "title": "Anomaly ratio - Inrush  Current Phase L1",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L1_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
    }
   ]
  },
  {
   "title": "Anomaly ratio - Inrush  Current Phase L2",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L2_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
    }
   ]
  },
  {
   "title": "Anomaly ratio - Inrush  Current Phase L3",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L3_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
    }
   ]
  },
  {
   "title": "Anomaly trend  [%] - Inrush current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L1_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L1_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L1_InrushCurr_AnomalyRatio\"])\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L2_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L2_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L2_InrushCurr_AnomalyRatio\"])"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC1\")\r\n  |> filter(fn: (r) => r._field == \"L3_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L3_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L3_InrushCurr_AnomalyRatio\"])"
    }
   ]
  },
  {
   "title": "Power [ W / VA / Var ]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_ActPower\" or r[\"_field\"] == \"L2_ActPower\" or r[\"_field\"] == \"L3_ActPower\" or\r\n  r[\"_field\"] == \"L1_ApparPower\" or r[\"_field\"] == \"L2_ApparPower\" or r[\"_field\"] == \"L3_ApparPower\" or\r\n  r[\"_field\"] == \"L1_ReactPower\" or r[\"_field\"] == \"L2_ReactPower\" or r[\"_field\"] == \"L3_ReactPower\" )\r\n\r\n"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 49 },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_PowFactor\" or  r[\"_field\"] == \"L2_PowFactor\" or r[\"_field\"] == \"L3_PowFactor\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "BC2 - Infeed Belt 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drv Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DriveState\")\r\n\r\n  //|> map(fn: (r) => ( { r with DriveStatus: if r._value == \"Running\" then 1\r\n  //                                          else if r._value == \"Stopped\" then 0\r\n   //                                         else\r\n   //                                             0\r\n   //                     })  )"
      }
     ]
    },
    {
     "title": "Current Assymetry [%]",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 7, "x": 17, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentAssymetry\")\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> yield(name: \"raw\")\r\n  |> movingAverage(n: 10)\r\n  |> yield(name: \"avarage\")\r\n"
      }
     ]
    },
    {
     "title": "Current [ A ]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_Current\" or  r[\"_field\"] == \"L2_Current\" or r[\"_field\"] == \"L3_Current\")\r\n   |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n"
      }
     ]
    },
    {
     "title": "Current Integral",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 16 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_CurrIntegral\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Current Integral Phase L1",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L1_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Current Integral Phase L2",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L2_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Current Integral Phase L3",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L3_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly trend  [%] - Current integral",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L1_CurrIntegral_AnomalyRatio\"  ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L1_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L1_CurrIntegral_AnomalyRatio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L2_CurrIntegral_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L2_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L2_CurrIntegral_AnomalyRatio\"])"
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L3_CurrIntegral_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L3_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L3_CurrIntegral_AnomalyRatio\"])"
      }
     ]
    },
    {
     "title": "Inrush Current [A]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 29 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_InrushCurr\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Inrush  Current Phase L1",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L1_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Inrush  Current Phase L2",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L2_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Inrush  Current Phase L3",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L3_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly trend  [%] - Inrush current",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 35 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L1_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L1_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L1_InrushCurr_AnomalyRatio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L2_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L2_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L2_InrushCurr_AnomalyRatio\"])"
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC2\")\r\n  |> filter(fn: (r) => r._field == \"L3_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L3_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L3_InrushCurr_AnomalyRatio\"])"
      }
     ]
    },
    {
     "title": "Power [ W / VA / Var ]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 41 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_ActPower\" or r[\"_field\"] == \"L2_ActPower\" or r[\"_field\"] == \"L3_ActPower\" or\r\n  r[\"_field\"] == \"L1_ApparPower\" or r[\"_field\"] == \"L2_ApparPower\" or r[\"_field\"] == \"L3_ApparPower\" or\r\n  r[\"_field\"] == \"L1_ReactPower\" or r[\"_field\"] == \"L2_ReactPower\" or r[\"_field\"] == \"L3_ReactPower\" )\r\n\r\n"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 49 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_PowFactor\" or  r[\"_field\"] == \"L2_PowFactor\" or r[\"_field\"] == \"L3_PowFactor\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "THD current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 55 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_CurrentTHD\" or  r[\"_field\"] == \"L2_CurrentTHD\" or r[\"_field\"] == \"L3_CurrentTHD\")\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "BC3 - Infeed Belt 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drv Status",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 17, "x": 0, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DriveState\")\r\n\r\n  //|> map(fn: (r) => ( { r with DriveStatus: if r._value == \"Running\" then 1\r\n  //                                          else if r._value == \"Stopped\" then 0\r\n   //                                         else\r\n   //                                             0\r\n   //                     })  )"
      }
     ]
    },
    {
     "title": "Current Assymetry [%]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CurrentAssymetry\")\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> yield(name: \"raw\")\r\n  |> movingAverage(n: 10)\r\n  |> yield(name: \"avarage\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Current [ A ]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 7 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_Current\" or  r[\"_field\"] == \"L2_Current\" or r[\"_field\"] == \"L3_Current\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "Current Integral",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 15 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_CurrIntegral\" or r[\"_field\"] == \"L2_CurrIntegral\" or r[\"_field\"] == \"L3_CurrIntegral\"  )\r\n\r\n"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Current Integral Phase L1",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L1_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Current Integral Phase L2",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L2_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Current Integral Phase L3",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L3_CurrIntegral_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly trend  [%] - Current Integral",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 21 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L1_CurrIntegral_AnomalyRatio\"  ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L1_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L1_CurrIntegral_AnomalyRatio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L2_CurrIntegral_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L2_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L2_CurrIntegral_AnomalyRatio\"])"
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L3_CurrIntegral_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L3_CurrIntegral_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L3_CurrIntegral_AnomalyRatio\"])"
      }
     ]
    },
    {
     "title": "Inrush Current [A]",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 28 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_InrushCurr\" or r[\"_field\"] == \"L2_InrushCurr\" or r[\"_field\"] == \"L3_InrushCurr\" )\r\n\r\n"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Inrush  Current Phase L1",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L1_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Inrush  Current Phase L2",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L2_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly ratio - Inrush  Current Phase L3",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 7, "x": 17, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L3_InrushCurr_Anomaly\")\r\n  \r\n |> reduce(\r\n             fn: (r, accumulator) => ( {\r\n                                        sum_anom: r._value + accumulator.sum_anom, \r\n                                        count_anom: accumulator.count_anom + 1,\r\n                                        ratio:  100.0 * float(v: r._value + accumulator.sum_anom ) / float (v: accumulator.count_anom + 1 ),\r\n                                        } ),\r\n             identity: {sum_anom: 0.0 , count_anom: 0, ratio: 0.0},\r\n  )\r\n\r\n|> drop (columns: [\"sum_anom\" , \"count_anom\"] )"
      }
     ]
    },
    {
     "title": "Anomaly trend  [%] - Inrush current",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L1_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L1_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L1_InrushCurr_AnomalyRatio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L2_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L2_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L2_InrushCurr_AnomalyRatio\"])"
      },
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ElectricalMeasurement\" and r.SensorName == \"BC3\")\r\n  |> filter(fn: (r) => r._field == \"L3_InrushCurr_AnomalyRatio\" ) \r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with anomalyPercent: r.L3_InrushCurr_AnomalyRatio * 100.0 } )  )\r\n  |> drop(columns: [\"L3_InrushCurr_AnomalyRatio\"])"
      }
     ]
    },
    {
     "title": "Power [ W / VA / Var ]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 40 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_ActPower\" or r[\"_field\"] == \"L2_ActPower\" or r[\"_field\"] == \"L3_ActPower\" or\r\n  r[\"_field\"] == \"L1_ApparPower\" or r[\"_field\"] == \"L2_ApparPower\" or r[\"_field\"] == \"L3_ApparPower\" or\r\n  r[\"_field\"] == \"L1_ReactPower\" or r[\"_field\"] == \"L2_ReactPower\" or r[\"_field\"] == \"L3_ReactPower\" )\r\n\r\n"
      }
     ]
    },
    {
     "title": "Power Factor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 48 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_PowFactor\" or  r[\"_field\"] == \"L2_PowFactor\" or r[\"_field\"] == \"L3_PowFactor\")\r\n\r\n"
      }
     ]
    },
    {
     "title": "THD current",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 54 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\")\r\n  |> filter(fn: (r) => r[\"SensorName\"] == \"BC3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"L1_CurrentTHD\" or  r[\"_field\"] == \"L2_CurrentTHD\" or r[\"_field\"] == \"L3_CurrentTHD\")\r\n\r\n"
      }
     ]
    }
   ]
  }
 ]
}