{
 "title": "PPS L1 - Main",
 "tags": [ "PPSL1_Main" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Process_Bucket", "query": "${VAR_PROCESS_BUCKET}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: #FFFFFF; background-color: #1D9FEF; font-size: 17px;text-align:center\">\r\nMax Anomaly Vibration [%]\r\n<br>\r\n .\r\n</h2>\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: #FFFFFF; background-color: #1D9FEF; font-size: 17px;text-align:center\">\r\nMax Anomaly [%]\r\n<br>\r\nAir Actuators Operating Time\r\n</h2>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: #FFFFFF; background-color: #1D9FEF; font-size: 17px;text-align:center\">\r\nMax Anomaly [%]\r\n<br>\r\nElectrical Current Integral-Rot.Table\r\n</h2>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<h2 style=\"color: #FFFFFF; background-color: #1D9FEF; font-size: 17px;text-align:center\">\r\nMax Anomaly [%]\r\n<br>\r\nElectrical Current Inrush Current-Rot.Table\r\n</h2>\r\n\r\n\r\n\r\n"
   }
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS1\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS1_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS2\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS2_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS3\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS3_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS4\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS4_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS5\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS5_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS6\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS6_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS7\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS7_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS8\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS8_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS9\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS9_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS10\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS10_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS11\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS11_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS12\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS12_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VibAccelAnalytics\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for vibration sensors\r\n  |> filter(fn: (r) => r.SensorName == \"BS13\")\r\n  |>max()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  |> yield(name: \"BS13_max_anomaly_ratio\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActuatorOperTimes\" and r.StationName == \"10N1\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for actuator operation time\r\nSlideUnitLeft_Extend = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitLeft\" and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitLeft_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnitLeft_Retract = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitLeft\" and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitLeft_Retract_max_anomaly_ratio\")\r\n\r\nSlideUnitRight_Extend  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitRight\" and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitRight_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnitRight_Retract   = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitRight\" and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitRight_Retract_max_anomaly_ratio\")\r\n\r\nHardStop_Extend  = data |> filter(fn: (r) => r.DeviceName == \"HardStop\" and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"HardStop_Extend_max_anomaly_ratio\")\r\n\r\nHardStop_Retract  = data |> filter(fn: (r) => r.DeviceName == \"HardStop\" and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"HardStop_Retract_max_anomaly_ratio\")\r\n\r\n\r\ntotal1 = union (tables: [SlideUnitLeft_Extend, SlideUnitLeft_Retract])\r\ntotal2 = union (tables: [total1, SlideUnitRight_Extend])\r\ntotal3 = union (tables: [total2, SlideUnitRight_Retract])\r\ntotal4 = union (tables: [total3, HardStop_Extend])\r\ntotal5 = union (tables: [total4, HardStop_Retract])\r\n|> map(fn: (r) => ({ AnomalyRatioMax_10N1: r._value }))\r\n|>max(column: \"AnomalyRatioMax_10N1\" )\r\n|>yield(name:\"total\" )\r\n"
    },
    {
     "query": "data = from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActuatorOperTimes\" and r.StationName == \"10N3\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for actuator operation time\r\nPartClamp1_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp1_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp1_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp2_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp2_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp2_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideUnitHor_Extend  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitHor\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitHor_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnitHor_Retract  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitHor\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitHor_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideUnitVert_Extend  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitVert\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitVert_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnitVert_Retract  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitVert\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitVert_Retract_max_anomaly_ratio\")\r\n\r\n\r\n// find max of all max values\r\ntotal1 = union (tables: [PartClamp1_Extend, PartClamp1_Retract])\r\ntotal2 = union (tables: [total1, PartClamp2_Extend])\r\ntotal3 = union (tables: [total2, PartClamp2_Retract])\r\ntotal4 = union (tables: [total3, SlideUnitHor_Extend])\r\ntotal5 = union (tables: [total4, SlideUnitHor_Retract])\r\ntotal6 = union (tables: [total5, SlideUnitVert_Extend])\r\ntotal7 = union (tables: [total6, SlideUnitVert_Retract])\r\n\r\n\r\n|> map(fn: (r) => ({ AnomalyRatioMax_10N3: r._value }))\r\n|>max(column: \"AnomalyRatioMax_10N3\" )\r\n|>yield(name:\"total\" )"
    },
    {
     "query": "data = from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActuatorOperTimes\" and r.StationName == \"10N7\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for actuator operation time\r\nPartClamp11_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp11\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp11_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp11_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp11\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp11_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp12_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp12\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp12_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp12_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp12\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp12_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp21_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp21\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp21_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp21_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp21\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp21_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp22_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp22\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp22_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp22_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp22\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp22_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp31_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp31\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp31_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp31_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp31\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp31_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp32_Extend  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp32\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp32_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp32_Retract  = data |> filter(fn: (r) => r.DeviceName == \"PartClamp32\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp32_Retract_max_anomaly_ratio\")\r\n\r\n\r\n// find max of all max values\r\ntotal1 = union (tables: [PartClamp11_Extend, PartClamp11_Retract])\r\ntotal2 = union (tables: [total1, PartClamp12_Extend])\r\ntotal3 = union (tables: [total2, PartClamp12_Retract])\r\ntotal4 = union (tables: [total3, PartClamp21_Extend])\r\ntotal5 = union (tables: [total4, PartClamp21_Retract])\r\ntotal6 = union (tables: [total5, PartClamp22_Extend])\r\ntotal7 = union (tables: [total6, PartClamp22_Retract])\r\n\r\ntotal8 = union (tables: [total7, PartClamp31_Extend])\r\ntotal9 = union (tables: [total8, PartClamp31_Retract])\r\ntotal10 = union (tables: [total9, PartClamp32_Extend])\r\ntotal11 = union (tables: [total10, PartClamp32_Retract])\r\n\r\n\r\n|> map(fn: (r) => ({ AnomalyRatioMax_10N7: r._value }))\r\n|>max(column: \"AnomalyRatioMax_10N7\" )\r\n|>yield(name:\"total\" )"
    },
    {
     "query": "data = from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActuatorOperTimes\" and r.StationName == \"10N10\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for actuator operation time\r\nPartClamp1_Extend   = data |> filter(fn: (r) => r.DeviceName == \"PartClamp1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp1_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp1_Retract   = data |> filter(fn: (r) => r.DeviceName == \"PartClamp1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nPartClamp2_Extend   = data |> filter(fn: (r) => r.DeviceName == \"PartClamp2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp2_Extend_max_anomaly_ratio\")\r\n\r\nPartClamp2_Retract   = data |> filter(fn: (r) => r.DeviceName == \"PartClamp2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"PartClamp2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nTurning1_Extend   = data |> filter(fn: (r) => r.DeviceName == \"Turning1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning1_Extend_max_anomaly_ratio\")\r\n\r\nTurning1_Retract   = data |> filter(fn: (r) => r.DeviceName == \"Turning1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nTurning2_Extend   = data |> filter(fn: (r) => r.DeviceName == \"Turning2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning2_Extend_max_anomaly_ratio\")\r\n\r\nTurning2_Retract   = data |> filter(fn: (r) => r.DeviceName == \"Turning2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning2_Retract_max_anomaly_ratio\")\r\n\r\n\r\n// find max of all max values\r\ntotal1 = union (tables: [PartClamp1_Extend, PartClamp1_Retract])\r\ntotal2 = union (tables: [total1, PartClamp2_Extend])\r\ntotal3 = union (tables: [total2, PartClamp2_Retract])\r\ntotal4 = union (tables: [total3, Turning1_Extend])\r\ntotal5 = union (tables: [total4, Turning1_Retract])\r\ntotal6 = union (tables: [total5, Turning2_Extend])\r\ntotal7 = union (tables: [total6, Turning2_Retract])\r\n\r\n\r\n|> map(fn: (r) => ({ AnomalyRatioMax_10N10: r._value }))\r\n|>max(column: \"AnomalyRatioMax_10N10\" )\r\n|>yield(name:\"total\" )"
    },
    {
     "query": "data = from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActuatorOperTimes\" and r.StationName == \"10N11\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for actuator operation time\r\nGripper1_Extend = data |> filter(fn: (r) => r.DeviceName == \"Gripper1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Gripper1_Extend_max_anomaly_ratio\")\r\n\r\nGripper1_Retract = data |> filter(fn: (r) => r.DeviceName == \"Gripper1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Gripper1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nGripper2_Extend = data |> filter(fn: (r) => r.DeviceName == \"Gripper2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Gripper2_Extend_max_anomaly_ratio\")\r\n\r\nGripper2_Retract = data |> filter(fn: (r) => r.DeviceName == \"Gripper2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Gripper2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideHor1_Extend = data |> filter(fn: (r) => r.DeviceName == \"SlideHor1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideHor1_Extend_max_anomaly_ratio\")\r\n\r\nSlideHor1_Retract = data |> filter(fn: (r) => r.DeviceName == \"SlideHor1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideHor1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideHor2_Extend = data |> filter(fn: (r) => r.DeviceName == \"SlideHor2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideHor2_Extend_max_anomaly_ratio\")\r\n\r\nSlideHor2_Retract = data |> filter(fn: (r) => r.DeviceName == \"SlideHor2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideHor2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSwivelUnit1_Extend = data |> filter(fn: (r) => r.DeviceName == \"SwivelUnit1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SwivelUnit1_Extend_max_anomaly_ratio\")\r\n\r\nSwivelUnit1_Retract = data |> filter(fn: (r) => r.DeviceName == \"SwivelUnit1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SwivelUnit1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSwivelUnit2_Extend = data |> filter(fn: (r) => r.DeviceName == \"SwivelUnit2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SwivelUnit2_Extend_max_anomaly_ratio\")\r\n\r\nSwivelUnit2_Retract = data |> filter(fn: (r) => r.DeviceName == \"SwivelUnit2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SwivelUnit2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideUnitVert_Extend  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitVert\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitVert_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnitVert_Retract  = data |> filter(fn: (r) => r.DeviceName == \"SlideUnitVert\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnitVert_Retract_max_anomaly_ratio\")\r\n\r\n\r\n// find max of all max values\r\ntotal1 = union (tables: [Gripper1_Extend, Gripper1_Retract])\r\ntotal2 = union (tables: [total1, Gripper2_Extend])\r\ntotal3 = union (tables: [total2, Gripper2_Retract])\r\ntotal4 = union (tables: [total3, SlideHor1_Extend])\r\ntotal5 = union (tables: [total4, SlideHor1_Retract])\r\ntotal6 = union (tables: [total5, SlideHor2_Extend])\r\ntotal7 = union (tables: [total6, SlideHor2_Retract])\r\ntotal8 = union (tables: [total7, SwivelUnit1_Extend])\r\ntotal9 = union (tables: [total8, SwivelUnit1_Retract])\r\ntotal10 = union (tables: [total9, SwivelUnit2_Extend])\r\ntotal11 = union (tables: [total10, SwivelUnit2_Retract])\r\ntotal12 = union (tables: [total11, SlideUnitVert_Extend])\r\ntotal13 = union (tables: [total12, SlideUnitVert_Retract])\r\n\r\n\r\n|> map(fn: (r) => ({ AnomalyRatioMax_10N11: r._value }))\r\n|>max(column: \"AnomalyRatioMax_10N11\" )\r\n|>yield(name:\"total\" )"
    },
    {
     "query": "data = from(bucket: \"PPSL1\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ActuatorOperTimes\" and r.StationName == \"10N31\" and r._field == \"Anomaly_ratio\")\r\n\r\n// find max value of anomaly ratio for actuator operation time\r\nSeparator1_Extend = data |> filter(fn: (r) => r.DeviceName == \"Separator1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Separator1_Extend_max_anomaly_ratio\")\r\n\r\nSeparator1_Retract = data |> filter(fn: (r) => r.DeviceName == \"Separator1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Separator1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSeparator2_Extend = data |> filter(fn: (r) => r.DeviceName == \"Separator2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Separator2_Extend_max_anomaly_ratio\")\r\n\r\nSeparator2_Retract = data |> filter(fn: (r) => r.DeviceName == \"Separator2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Separator2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nLifting1_Extend  = data |> filter(fn: (r) => r.DeviceName == \"Lifting1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Lifting1_Extend_max_anomaly_ratio\")\r\n\r\nLifting1_Retract  = data |> filter(fn: (r) => r.DeviceName == \"Lifting1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Lifting1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nLifting2_Extend  = data |> filter(fn: (r) => r.DeviceName == \"Lifting2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Lifting2_Extend_max_anomaly_ratio\")\r\n\r\nLifting2_Retract  = data |> filter(fn: (r) => r.DeviceName == \"Lifting2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Lifting2_Retract_max_anomaly_ratio\")\r\n\r\nTurning1_Extend  = data |> filter(fn: (r) => r.DeviceName == \"Turning1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning1_Extend_max_anomaly_ratio\")\r\n\r\nTurning1_Retract = data |> filter(fn: (r) => r.DeviceName == \"Turning1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nTurning2_Extend  = data |> filter(fn: (r) => r.DeviceName == \"Turning2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning2_Extend_max_anomaly_ratio\")\r\n\r\nTurning2_Retract = data |> filter(fn: (r) => r.DeviceName == \"Turning2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"Turning2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nHardStop1_Extend  = data |> filter(fn: (r) => r.DeviceName == \"HardStop1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"HardStop1_Extend_max_anomaly_ratio\")\r\n\r\nHardStop1_Retract  = data |> filter(fn: (r) => r.DeviceName == \"HardStop1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"HardStop1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nHardStop2_Extend  = data |> filter(fn: (r) => r.DeviceName == \"HardStop2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"HardStop2_Extend_max_anomaly_ratio\")\r\n\r\nHardStop2_Retract  = data |> filter(fn: (r) => r.DeviceName == \"HardStop2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"HardStop2_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideUnit1_Extend = data |> filter(fn: (r) => r.DeviceName == \"SlideUnit1\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnit1_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnit1_Retract = data |> filter(fn: (r) => r.DeviceName == \"SlideUnit1\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnit1_Retract_max_anomaly_ratio\")\r\n\r\n\r\nSlideUnit2_Extend = data |> filter(fn: (r) => r.DeviceName == \"SlideUnit2\"  and r.OperationType ==\"Extend_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnit2_Extend_max_anomaly_ratio\")\r\n\r\nSlideUnit2_Retract = data |> filter(fn: (r) => r.DeviceName == \"SlideUnit2\"  and r.OperationType ==\"Retract_T\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n  //|> yield(name: \"SlideUnit2_Retract_max_anomaly_ratio\")\r\n\r\n\r\n// find max of all max values\r\ntotal1 = union (tables: [Separator1_Extend, Separator1_Retract])\r\ntotal2 = union (tables: [total1, Separator2_Extend])\r\ntotal3 = union (tables: [total2, Separator2_Retract])\r\ntotal4 = union (tables: [total3, Lifting1_Extend])\r\ntotal5 = union (tables: [total4, Lifting1_Retract])\r\ntotal6 = union (tables: [total5, Lifting2_Extend])\r\ntotal7 = union (tables: [total6, Lifting2_Retract])\r\ntotal8 = union (tables: [total7, Turning1_Extend])\r\ntotal9 = union (tables: [total8, Turning1_Retract])\r\ntotal10 = union (tables: [total9, Turning2_Extend])\r\ntotal11 = union (tables: [total10, Turning2_Retract])\r\ntotal12 = union (tables: [total11, HardStop1_Extend])\r\ntotal13 = union (tables: [total12, HardStop1_Retract])\r\ntotal14 = union (tables: [total13, HardStop2_Extend])\r\ntotal15 = union (tables: [total14, HardStop2_Retract])\r\ntotal16 = union (tables: [total15, SlideUnit1_Extend])\r\ntotal17 = union (tables: [total16, SlideUnit1_Retract])\r\ntotal18 = union (tables: [total17, SlideUnit2_Extend])\r\ntotal19 = union (tables: [total18, SlideUnit2_Retract])\r\n\r\n|> map(fn: (r) => ({ AnomalyRatioMax_10N31: r._value }))\r\n|>max(column: \"AnomalyRatioMax_10N31\" )\r\n|>yield(name:\"total\" )"
    }
   ]
  },
  {
   "title": "BC1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\" and r.SensorName == \"BC1\" )\r\n\r\nBC1_MaxCurrInt_L1 = data |> filter(fn: (r) => r._field == \"L1_CurrIntegral_AnomalyRatio\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n\r\nBC1_MaxCurrInt_L2 = data |> filter(fn: (r) => r._field == \"L2_CurrIntegral_AnomalyRatio\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n\r\nBC1_MaxCurrInt_L3 = data |> filter(fn: (r) => r._field == \"L3_CurrIntegral_AnomalyRatio\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n\r\ntotal1 = union (tables: [BC1_MaxCurrInt_L1, BC1_MaxCurrInt_L2])\r\ntotal2 = union (tables: [total1, BC1_MaxCurrInt_L3])\r\n\r\n|>map(fn: (r) => ({ MaxAnomalyRatio_CurrentIntegral_BC1BC2BC3: r._value }))\r\n|>max(column: \"MaxAnomalyRatio_CurrentIntegral_BC1BC2BC3\")\r\n|>yield(name:\"total\")"
    }
   ]
  },
  {
   "title": "BC1",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"PPSL1\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ElectricalMeasurement\" and r.SensorName == \"BC1\" )\r\n\r\nBC1_MaxInrushCurr_L1 = data |> filter(fn: (r) => r._field == \"L1_InrushCurr_AnomalyRatio\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n\r\nBC1_MaxInrushCurr_L2 = data |> filter(fn: (r) => r._field == \"L2_InrushCurr_AnomalyRatio\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n\r\nBC1_MaxInrushCurr_L3 = data |> filter(fn: (r) => r._field == \"L3_InrushCurr_AnomalyRatio\")\r\n  |>max()\r\n  |>last()\r\n  |>map(fn: (r) => ({r with _value: r._value * 100.0}))\r\n\r\ntotal1 = union (tables: [BC1_MaxInrushCurr_L1, BC1_MaxInrushCurr_L2])\r\ntotal2 = union (tables: [total1, BC1_MaxInrushCurr_L3])\r\n\r\n|> map(fn: (r) => ({ MaxAnomalyRatio_InrushCurrent_BC1BC2BC3: r._value }))\r\n|> max(column: \"MaxAnomalyRatio_InrushCurrent_BC1BC2BC3\")\r\n|>yield(name:\"total\")"
    }
   ]
  },
  {
   "title": "Machine Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "AutoManState = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MachineStatus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AutoMode\" )\r\n  |> map(fn: (r) => ({ r with _field: \"AutoManual\" }))\r\n  |> map(fn: (r) => ({ r with _value: if r._value == 1 \r\n                                                    then \"Auto\"\r\n                                                    else \"Manual\"\r\n                                                     }))\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  |> yield(name: \"AutoMan\")\r\n\r\n"
    },
    {
     "query": "Producing = from(bucket: \"${Process_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MachineStatus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Producing\" )\r\n  |> map(fn: (r) => ({ r with _value: if r._value == 1 \r\n                                                    then \"yes\"\r\n                                                    else \"no\"\r\n                                                     }))\r\n  \r\n  |> map(fn: (r) => ({ r with _field: \"Producing\" }))\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  |> yield(name: \"Producing\")\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"MachineStatus\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FieldbusOK\" )\r\n\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"MachineStatus\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MachineCommOK\" )\r\n\r\n  |> aggregateWindow(every: 500ms, fn: last, createEmpty: false)\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Temperature / Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"TempHumidSensor\" and r.SensorName == \"BM2\")\r\n  |> filter(fn: (r) => r._field == \"Humidity\" or r._field == \"Temperature\" )\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n // |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Dew Point ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"${Process_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"DewPointSensor\" and r.SensorName == \"BT1\" )\r\n  |> filter(fn: (r) =>  r._field == \"Temperature\" )\r\n // |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  }
 ]
}