{
 "title": "PPS L1 - Vibrations",
 "tags": [ "PPSL1_Vibrations" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Process_Bucket", "query": "${VAR_PROCESS_BUCKET}" },
   { "name": "Correlation_Bucket", "query": "${VAR_CORRELATION_BUCKET}" }
  ]
 },
 "panels": [
  {
   "title": "Anomaly trend  [%]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS1\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS2\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS3\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS4\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS5\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS6\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS7\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS8\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS9\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS10\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS11\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS11\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS12\")\r\n\r\n\r\n\r\n\r\n  "
    },
    {
     "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n  |> yield(name: \"BS13\")\r\n\r\n\r\n\r\n\r\n  "
    }
   ]
  },
  {
   "title": "Rotary Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 38 },
     "options": {
      "content": "<font size = \"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS1\r\n<br>\r\n</font> \r\n\r\n<font size=\"3\">\r\nmain gearbox\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 38 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 38 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 38 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 39 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS1\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 47 },
     "options": {
      "content": "<font size = \"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS2\r\n<br>\r\n</font>  \r\n\r\n<font size=\"3\">\r\nIntermediate gearbox\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 47 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 47 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 47 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 48 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS2\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 56 },
     "options": {
      "content": "<font size = \"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS3\r\n<br>\r\n</font>  \r\n\r\n<font size=\"3\">\r\nFront of motor\r\n</font>\r\n\r\n"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 56 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 56 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 56 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 57 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS3\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 65 },
     "options": {
      "content": "<font size = \"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS4\r\n<br>\r\n</font>  \r\n\r\n<font size=\"3\">\r\nRear of motor\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 65 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 65 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 65 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 66 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS4\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Control Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 31 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS5\r\n  <br>\r\n</font>  \r\n\r\n<font size=\"3\">\r\nGearbox\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 31 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 31 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 31 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 32 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS5\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 40 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS6\r\n<br>  \r\n</font>  \r\n\r\n<font size=\"3\">\r\nFront bearing\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 40 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 40 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 40 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 41 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS6\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Ring Infeed belt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 24 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS7\r\n<br>  \r\n</font>  \r\n\r\n<font size=\"3\">\r\nGearbox\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 24 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 24 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 24 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  \r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 25 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS7\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 33 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS8\r\n<br>  \r\n</font>  \r\n\r\n<font size=\"3\">\r\nFront bearing\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 33 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 33 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 33 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 34 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS8\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "Discharge belt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 17 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS9\r\n<br>  \r\n</font>  \r\n\r\n<font size=\"3\">\r\nGearbox\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 17 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 17 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 18 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS9\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 26 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS10\r\n<br>  \r\n</font>  \r\n\r\n<font size=\"3\">\r\nFront bearing\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 26 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 26 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 26 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 27 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS10\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 10 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS11\r\n  <br>\r\n</font>\r\n\r\n<font size=\"3\">\r\nmachine body\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS11\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 10 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS11\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 10 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS11\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS11\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 11 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS11\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 19 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS12\r\n  <br>\r\n</font>\r\n\r\n<font size=\"3\">\r\nmesh\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 19 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 19 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 19 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 20 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS12\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 2, "x": 0, "y": 28 },
     "options": {
      "content": "<font size=\"5\">\r\n<br>\r\n<br>\r\n<br>\r\n  BS13\r\n  <br>\r\n</font>\r\n\r\n<font size=\"3\">\r\nVacuum extractor\r\n</font>"
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 1, "w": 6, "x": 2, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Std_ratio\" )\r\n\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n  //|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  //|> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  //|> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  //|> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"result\")\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Anomaly trend  [%]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 28 },
     "targets": [
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n\r\n\r\n\r\n\r\n  "
      },
      {
       "query": "from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibVelolAnalytics\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r._field == \"Anomaly_ratio\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n  |> map (fn: (r) =>  ( { r with AnomalyPercent: r.Anomaly_ratio * 100.0 } )  )\r\n  |> drop(columns: [\"Anomaly_ratio\"])\r\n"
      }
     ]
    },
    {
     "title": "Temperature [° C]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 14, "y": 28 },
     "targets": [
      {
       "query": "import \"experimental/aggregate\"\r\n\r\nstream = from(bucket:\"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r._field == \"ContactTemperature\")\r\n  |> aggregateWindow(every: 5s, fn: last, createEmpty: false)\r\n\r\n\r\ntemperature = stream\r\n  |> map(fn: (r) => ( { r with Temperature: r._value }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\", \"_measurement\", \"SensorName\"])\r\n  |> yield(name:\" temperature\")\r\n \r\nrateofchange = stream\r\n  |> aggregate.rate (every: 1m, unit: 1m)\r\n  |> map(fn: (r) => ( { r with RateOfChange: r._value * 1.0 }))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\"])\r\n  |> yield(name: \"rate\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Correlation MaxCoefficient",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 28 },
     "targets": [
      {
       "query": "from(bucket: \"${Correlation_Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibrationsCorrelation\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r._field == \"MaxCoeff\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    },
    {
     "title": "Vibration Energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 2, "y": 29 },
     "targets": [
      {
       "query": "from(bucket: \"${Process_Bucket}\" )\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"VibAccelAnalytics\" and r.SensorName == \"BS13\")\r\n  |> filter(fn: (r) => r._field == \"RMS_total\" or r[\"_field\"] == \"Avg_model\" or r[\"_field\"] == \"Std_model\" )\r\n  |> aggregateWindow(every: 10ms, fn: last, createEmpty: false)\r\n\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map (fn: (r) =>  ( { r with PLus3Std: r.Avg_model  + 3.0 * r.Std_model} )  )\r\n  |> map (fn: (r) =>  ( { r with Minus3Std: r.Avg_model  - 3.0 * r.Std_model} )  )\r\n  |> drop(columns: [\"Std_model\"])\r\n  |> yield(name: \"last\")\r\n\r\n\r\n\r\n\r\n\r\n  "
      }
     ]
    }
   ]
  }
 ]
}